### ISSUE TITLE
fix basic.js

### ISSUE THREAD

**Issue by rom1504** [mhsjlw/flying-squid#147]
@109C says it's broken

**Comment by 109C** [comment]
Stack trace:
```
/Users/109C/Desktop/fs_7_dec/node_modules/babel-runtime/node_modules/core-js/library/modules/$.defined.js:3
  if(it == undefined)throw TypeError("Can't call method on  " + it);
                                                              ^
TypeError: Can't call method on  undefined
    at TypeError (native)
    at module.exports (/Users/109C/Desktop/fs_7_dec/node_modules/babel-runtime/node_modules/core-js/library/modules/$.defined.js:3:63)
    at module.exports (/Users/109C/Desktop/fs_7_dec/node_modules/babel-runtime/node_modules/core-js/library/modules/$.to-object.js:4:17)
    at keys (/Users/109C/Desktop/fs_7_dec/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.object.keys.js:6:18)
    at Object.module.exports.server (/Users/109C/Desktop/fs_7_dec/dist/lib/plugins/external.js:27:3)
    at /Users/109C/Desktop/fs_7_dec/dist/index.js:53:36
    at Array.forEach (native)
    at MCServer.connect (/Users/109C/Desktop/fs_7_dec/dist/index.js:52:10)
    at Object.createMCServer (/Users/109C/Desktop/fs_7_dec/dist/index.js:30:12)
    at Object.<anonymous> (/Users/109C/Desktop/fs_7_dec/examples/basic.js:3:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```
