### ISSUE TITLE
Prevent squids from taking over

### ISSUE THREAD

**Issue by mhsjlw** [mhsjlw/flying-squid#28]
Currently when you hit a squid the server crashes.

    /root/workspace/flying-squid/lib/playerPlugins/pvp.js:17
        var attackedPlayer = serv.entities[entityId].player;
                                                ^
    TypeError: Cannot read property 'player' of undefined
        at attackEntity (/root/workspace/flying-squid/lib/playerPlugins/pvp.js:17:49)
        at Client.<anonymous> (/root/workspace/flying-squid/lib/playerPlugins/pvp.js:35:7)
        at Client.EventEmitter.emit (events.js:95:17)
        at Deserializer.<anonymous> (/root/workspace/flying-squid/node_modules/minecraft-   protocol/dist/client.js:149:12)
        at Deserializer.EventEmitter.emit (events.js:95:17)
        at readableAddChunk (/root/workspace/flying-squid/node_modules/minecraft- protocol/node_modules/readable-stream/lib/_stream_readable.js:195:16)
        at Deserializer.Readable.push (/root/workspace/flying-squid/node_modules/minecraft-protocol/node_modules/readable-stream/lib/_stream_readable.js:162:10)
        at Deserializer.Transform.push (/root/workspace/flying-squid/node_modules/minecraft-protocol/node_modules/readable-stream/lib/_stream_transform.js:145:32)
        at Deserializer._transform (/root/workspace/flying-squid/node_modules/minecraft-protocol/dist/transforms/serializer.js:255:14)
        at Deserializer.Transform._read (/root/workspace/flying-squid/node_modules/minecraft-    protocol/node_modules/readable-stream/lib/_stream_transform.js:184:10)

**Comment by rom1504** [comment]
Yes, to handle that you are going to need a proper entity handling : you're going to need to add the squid in serv.entities when you create it.
And make sure code the uses serv.entities don't assume things about the entity.

**Comment by mhsjlw** [comment]
We'll fix it later.

**Comment by rom1504** [comment]
Hmm why close ? This is (at least) a reminder to implement entities.

**Comment by mhsjlw** [comment]
@rom1504 I was going to reopen it later. I just thought that we don't need it right now, as it isn't our top priority

**Comment by rom1504** [comment]
done
